# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 576ba2ebf3edd01c649fd234c5133c41d96c081475a92c0322063f1fdb417096d0af59fc4949bf717d206e56397d98111c8094aca979dcc7996650dc7879da03

test:
  secret_key_base: e6494e1aae8a99b135dceede596485acc991f1c4ad3ba31031de0e950f9626ed746191f4a68c0e3d5043e5344f9cbff93ca14c2718800fd13a91f8bba7d4560e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
